services:
  db:
    image: postgis/postgis:16-3.5-alpine
    container_name: unibus-db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  memcached:
    image: memcached:1.6-alpine
    container_name: unibus-memcached
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    ports:
      - "11211:11211"
volumes:
  db_data:
