---
name: "deploy api"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-api.yml
      - "api/**"
      - .dockerignore
      - Dockerfile
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - tsconfig.json

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: main
          git_push_flags: --force
          git_remote_url: "ssh://dokku@${{ secrets.SSH_HOST }}:22/api"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
